# Generated by Django 3.2.6 on 2021-09-01 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_id', models.CharField(max_length=20)),
                ('difficulty_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DomainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=20)),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('question_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('question', models.TextField(max_length=1000)),
                ('category_id', models.CharField(max_length=10)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('flag', models.BooleanField(default=1)),
                ('category_names', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill.domaincategory')),
                ('difficulty_names', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill.difficultylevel')),
            ],
        ),
    ]
