# Generated by Django 3.2.6 on 2021-09-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=1000)),
                ('difficulty_id', models.CharField(choices=[('Easy', 'EA'), ('Medium', 'ME'), ('Hard', 'HA')], max_length=10)),
                ('category_id', models.CharField(choices=[('Python', 'PY'), ('Java', 'JV'), ('Dotnet', 'DN'), ('Testing', 'TS'), ('UI', 'UI'), ('IDM', 'IDM')], max_length=10)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('flag', models.BooleanField(default=1)),
            ],
        ),
    ]
