# Generated by Django 3.2.6 on 2021-09-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='category_id',
            field=models.CharField(choices=[('PY', 'Python'), ('JV', 'Java'), ('DN', 'Dotnet'), ('TS', 'Testing'), ('UI', 'UI'), ('IDM', 'IDM')], max_length=10),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='difficulty_id',
            field=models.CharField(choices=[('EA', 'Easy'), ('ME', 'Medium'), ('HA', 'Hard')], max_length=10),
        ),
    ]
