# Generated by Django 3.2.6 on 2021-09-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_auto_20210901_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbank',
            name='id',
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='question',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='question_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
