# Generated by Django 3.2.5 on 2021-09-02 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0008_alter_questionbank_category_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='difficulty_names',
            field=models.ForeignKey(default='choices', on_delete=django.db.models.deletion.CASCADE, to='skill.difficultylevel'),
        ),
    ]
