# Generated by Django 3.2.7 on 2021-09-06 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_id', models.CharField(max_length=20)),
                ('difficulty_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DomainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=20)),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ExamResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.CharField(max_length=50)),
                ('cad_id', models.CharField(max_length=50)),
                ('given_by', models.CharField(max_length=50)),
                ('given_date', models.DateField()),
                ('flag', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OptionsTable',
            fields=[
                ('option_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('question_id', models.CharField(max_length=50)),
                ('option1', models.CharField(max_length=50)),
                ('option2', models.CharField(max_length=50)),
                ('option3', models.CharField(max_length=50)),
                ('option4', models.CharField(max_length=50)),
                ('correct_option', models.CharField(max_length=50)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestLinkTable',
            fields=[
                ('test_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('category_id', models.CharField(max_length=10)),
                ('no_of_questions', models.CharField(max_length=10)),
                ('no_of_easy_questions', models.CharField(max_length=10)),
                ('no_of_medium_questions', models.CharField(max_length=10)),
                ('no_of_hard_questions', models.CharField(max_length=10)),
                ('date_of_exam', models.DateField()),
                ('start_time', models.CharField(max_length=50)),
                ('end_time', models.CharField(max_length=50)),
                ('test_link', models.URLField()),
                ('flag', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('question_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('question', models.TextField(max_length=1000)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('flag', models.BooleanField(default=1)),
                ('category_names', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='skill.domaincategory')),
                ('difficulty_names', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='skill.difficultylevel')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTable',
            fields=[
                ('emp_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=200)),
                ('flag', models.BooleanField(default=1)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill.domaincategory')),
            ],
            options={
                'db_table': 'Employeetable',
            },
        ),
        migrations.CreateModel(
            name='CandidatesTable',
            fields=[
                ('candidate_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=12)),
                ('candidate_mail', models.EmailField(max_length=254)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('flag', models.BooleanField(default=1)),
                ('domain_name', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='skill.domaincategory')),
            ],
            options={
                'db_table': 'Candidatestable',
            },
        ),
    ]
