# Generated by Django 3.2.7 on 2021-09-07 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CandidatesTable',
            new_name='CandidateTable',
        ),
    ]
