# Generated by Django 3.2.7 on 2021-09-01 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatesTable',
            fields=[
                ('candidate_id', models.IntegerField(primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=50)),
                ('flag', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'Candidatestable',
            },
        ),
        migrations.CreateModel(
            name='EmployeeTable',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=50)),
                ('flag', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'Employeetable',
            },
        ),
        migrations.CreateModel(
            name='ExamResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.CharField(max_length=50)),
                ('cad_id', models.CharField(max_length=50)),
                ('given_by', models.CharField(max_length=50)),
                ('given_date', models.CharField(max_length=50)),
                ('flag', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TestLinkTable',
            fields=[
                ('test_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('category_id', models.CharField(max_length=10)),
                ('no_of_questions', models.CharField(max_length=10)),
                ('no_of_easy_questions', models.CharField(max_length=10)),
                ('no_of_medium_questions', models.CharField(max_length=10)),
                ('no_of_hard_questions', models.CharField(max_length=10)),
                ('date_of_exam', models.DateField()),
                ('start_time', models.CharField(max_length=50)),
                ('end_time', models.CharField(max_length=50)),
                ('test_link', models.URLField()),
                ('flag', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OptionsTable',
            fields=[
                ('option_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('op1', models.CharField(max_length=50)),
                ('op2', models.CharField(max_length=50)),
                ('op3', models.CharField(max_length=50)),
                ('op4', models.CharField(max_length=50)),
                ('correct_option', models.CharField(max_length=50)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill.questionbank')),
            ],
        ),
    ]
