# Generated by Django 3.2.7 on 2021-09-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_rename_candidatestable_candidatetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatetable',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
