# Generated by Django 3.2.6 on 2021-09-02 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0003_remove_questionbank_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatestable',
            name='condidate_mail',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
