# Generated by Django 3.2.6 on 2021-09-02 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0004_candidatestable_condidate_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatestable',
            old_name='condidate_mail',
            new_name='candidate_mail',
        ),
    ]
