# Generated by Django 3.2.6 on 2021-09-02 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0005_rename_condidate_mail_candidatestable_candidate_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionstable',
            name='question_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='skill.questionbank'),
        ),
    ]
