# Generated by Django 3.2.6 on 2021-09-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0006_alter_optionstable_question_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionstable',
            old_name='op1',
            new_name='option1',
        ),
        migrations.RenameField(
            model_name='optionstable',
            old_name='op2',
            new_name='option2',
        ),
        migrations.RenameField(
            model_name='optionstable',
            old_name='op3',
            new_name='option3',
        ),
        migrations.RenameField(
            model_name='optionstable',
            old_name='op4',
            new_name='option4',
        ),
        migrations.AlterField(
            model_name='optionstable',
            name='correct_option',
            field=models.CharField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('option4', 'option4')], max_length=50),
        ),
    ]
