# Generated by Django 3.2.6 on 2021-09-03 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0007_auto_20210902_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatestable',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill.domaincategory'),
        ),
        migrations.AlterField(
            model_name='employeetable',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill.domaincategory'),
        ),
        migrations.AlterField(
            model_name='examresults',
            name='given_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='optionstable',
            name='correct_option',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='optionstable',
            name='question_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='category_names',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='skill.domaincategory'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='difficulty_names',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='skill.difficultylevel'),
        ),
    ]
