# Generated by Django 3.2.6 on 2021-09-03 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0008_auto_20210903_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionstable',
            name='question_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='skill.questionbank'),
        ),
    ]
