# Generated by Django 3.2.6 on 2021-09-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0009_alter_optionstable_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionstable',
            name='question_id',
            field=models.CharField(max_length=50),
        ),
    ]
