# Generated by Django 3.2.5 on 2021-09-02 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0009_alter_questionbank_difficulty_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='category_names',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill.domaincategory'),
        ),
    ]
