# Generated by Django 3.2.7 on 2021-09-03 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0010_alter_optionstable_question_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CandidatesTable',
        ),
    ]
