# Generated by Django 3.2.7 on 2021-09-03 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0011_delete_candidatestable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatesTable',
            fields=[
                ('candidate_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=12)),
                ('candidate_mail', models.EmailField(max_length=254)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('flag', models.BooleanField(default=1)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill.domaincategory')),
            ],
            options={
                'db_table': 'Candidatestable',
            },
        ),
    ]
