# Generated by Django 3.2.5 on 2021-09-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0011_alter_questionbank_difficulty_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresults',
            name='given_date',
            field=models.DateField(),
        ),
    ]
