# Generated by Django 3.2.7 on 2021-09-03 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0012_candidatestable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatestable',
            name='domain',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='skill.difficultylevel'),
        ),
    ]
