# Generated by Django 3.2.5 on 2021-09-02 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0012_alter_examresults_given_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatestable',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill.domaincategory'),
        ),
        migrations.AlterField(
            model_name='employeetable',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill.domaincategory'),
        ),
    ]
