# Generated by Django 3.2.5 on 2021-09-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0013_auto_20210902_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionstable',
            name='question_id',
        ),
        migrations.AlterField(
            model_name='optionstable',
            name='correct_option',
            field=models.CharField(choices=[('option1', '1'), ('option2', '2'), ('option3', '3'), ('option4', '4')], max_length=50),
        ),
    ]
