# Generated by Django 3.2.7 on 2021-09-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0014_alter_candidatestable_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatestable',
            old_name='domain',
            new_name='domain_name',
        ),
    ]
