# Generated by Django 3.2.7 on 2021-09-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0015_rename_domain_candidatestable_domain_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionstable',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='optionstable',
            name='modified_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='modified_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
