# Generated by Django 3.2.5 on 2021-09-06 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0016_auto_20210906_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testlinktable',
            old_name='category_id',
            new_name='category_name',
        ),
    ]
