# Generated by Django 3.2.7 on 2021-09-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0016_auto_20210906_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatestable',
            name='candidate_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employeetable',
            name='emp_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
