# Generated by Django 3.2.5 on 2021-09-06 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0017_rename_category_id_testlinktable_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlinktable',
            name='category_name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='skill.domaincategory'),
        ),
    ]
