# Generated by Django 3.2.5 on 2021-09-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0018_alter_testlinktable_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlinktable',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='testlinktable',
            name='flag',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='testlinktable',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
