# Generated by Django 3.2.5 on 2021-09-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0019_auto_20210906_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlinktable',
            name='flag',
            field=models.BooleanField(default=1),
        ),
    ]
